### ISSUE TITLE
Yahoo finance URL changed

### ISSUE THREAD

**Issue by Manoj98** [WayneDW/sentiment_analysis#10]
The carwler_yahoo_finance.py code is not working since the Yahoo finance URL has changed to 
"https://query1.finance.yahoo.com/v7/finance/download/GOOG?period1=1489516200&period2=1526322600&interval=1d&events=history&crumb=yytEulYpXr8"  
The new url requires me to have a cookie. Can you help me with the code so that it works as it was earlier?

**Comment by guohuiGH** [comment]
i solve the problem by  "https://github.com/c0redumb/yahoo_quote_download/edit/master/yahoo_quote_download/yqd.py"

**Comment by Manoj98** [comment]
I got the code running. Thank you so much @guohuiGH

**Comment by lorrp1** [comment]
Is this ai profitable?

**Comment by WayneDW** [comment]
It surely does if you could make it as good as possible. Anyway, it is very interesting.
