### ISSUE TITLE
2 questions, please help me

### ISSUE THREAD

**Issue by jinho3838** [WayneDW/sentiment_analysis#11]
1. 
In model_cnn.py code,

X = X.reshape(X.shape[0], 20, 50, 1).astype('float32')
The shape of X is (15,3000) , then 45000 array of size.
But X.shape[0] is 15 so that X.reshape(15,20,50,1). 45000 size cannot be reshaped of that.
I got an error.

How should i do?

2.
When i run model_cnn.py,
I get results like this following.

[[0 3]
 [0 0]]
Valid Label 0 Precision, nan%
Valid Label 1 Precision, 0.00%
/home/leo/TSD/sent_py3/model_cnn.py:85: RuntimeWarning: invalid value encountered in double_scalars
  print("Test Label %d Precision, %.2f%%" % (i, conf[i,i] * 100.0 / sum(conf[:,i])))
Test on 24 samples
[[ 0 10]
 [ 0 14]]
Test Label 0 Precision, nan%
Test Label 1 Precision, 58.33%

Many precisions are nan value.
Is it correct result?

**Comment by WayneDW** [comment]
Hi, @jinho3838 , I changed the framework to a new version, it is much more powerful and easier to understand, you are welcome to take a look at it.
