### ISSUE TITLE
Problem in importing util

### ISSUE THREAD

**Issue by Manoj98** [WayneDW/sentiment_analysis#12]
The "utils.py" file in the "bak" folder does not contain the attributes (dateGenerator, unify_word and padding) whereas you have used them in the "genFeatureMat_Glove.py" file to create feature matrix. 
Where can I find the actual "util.py" file? 
Thanks in advance

**Comment by WayneDW** [comment]
Sorry, I haven't update this project for a long time, the util.py is in the bak folder.

I plan to use the word vector trained from others, so you may also consider this way.

**Comment by WayneDW** [comment]
Hi, @Manoj98 , I changed the framework to a new version, it is much more powerful and easier to understand, you are welcome to take a look at it. Closes #12

**Comment by Manoj98** [comment]
Hey, Thanks for the update on the new version. Will work on it.
