### ISSUE TITLE
name 'BeautifulSoup' is not defined retry...

### ISSUE THREAD

**Issue by mxmxxt** [WayneDW/sentiment_analysis#13]
in ./crawler/reuters.py
How to solve this?

**Comment by WayneDW** [comment]
pip3 install bs4

**Comment by daventhedude** [comment]
still experiencing the same issue, after installing bs4 :/

**Comment by WayneDW** [comment]
You can google the error and try to figure it out, as far as I know bs4 is the key to install BeautifulSoup

**Comment by kkinlee** [comment]
I have the same issue. Just included the following in util.py and it is resolved:
from bs4 import BeautifulSoup

**Comment by ictinc** [comment]
Although this thread is closed I just felt I needed to mention that I just had the same issue on a fresh install and clone of the repository. 
Indeed the solution mentioned by @kkinlee solved it.

**Comment by snehasrinija2000** [comment]
i too have the same issue even after installing bs4

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/51355230/83905167-d76a3080-a77e-11ea-8592-69cc5210f57e.png)
Please help me on this

**Comment by AnuragPo** [comment]
from bs4 import BeautifulSoup
 and use r.text instead of r.content
