### ISSUE TITLE
issue with  AttributeError: 'float' object has no attribute 'item'

### ISSUE THREAD

**Issue by kkinlee** [WayneDW/sentiment_analysis#15]
Hi,

I encounter this problem when running main.py:

  File "C:\Users\Documents\Python Scripts\Sentiment-Analysis-in-Event-Driven-Stock-Price-Movement-Prediction-master\util.py", line 31, in <listcomp>
    set_scale = [parameter.data.std().item() for parameter in model.parameters()]

AttributeError: 'float' object has no attribute 'item'

error seems to came from util.py

Any idea on how to solve it?

Cheers

**Comment by WayneDW** [comment]
You are probably using older version of Pytorch

**Comment by kkinlee** [comment]
Thanks.
