### ISSUE TITLE
Downloadable news data

### ISSUE THREAD

**Issue by chenqinkai** [WayneDW/sentiment_analysis#19]
As mentioned in the README file, it can take a lot of time to crawl news data from Reuters. Is it possible to create another repo which contains all the news already crawled from the source, instead of letting everyone willing to use the data crawl by themselves ?
It will save a lot of time and unnecessary requests to the Reuters website.

**Comment by WayneDW** [comment]
I don't know if I am allowed to make the news public. That's why I didn't put it here. You can set the code on the server and ran it for a while.
