### ISSUE TITLE
hello there is a minus problem when running the code, could you please help? thanks

### ISSUE THREAD

**Issue by Yuminzhou** [WayneDW/sentiment_analysis#2]
the first file, called "crawler_reuters.py", it shows up: 

**Traceback (most recent call last):

  File "<ipython-input-42-9484baea6f09>", line 8, in <module>
    main()

  File "<ipython-input-42-9484baea6f09>", line 2, in main
    arg = sys.argv[2]

IndexError: list index out of range**

how can I fix it? Thanks

**Comment by WayneDW** [comment]
Are you sure you are using the most-updated version of crawler_reuters.py? Because in that version, I can't see any line with sys.argv[2]

**Comment by WayneDW** [comment]
Hi, @Yuminzhou , I changed the framework to a new version, it is much more powerful and easier to understand, you are welcome to take a look at it.
