### ISSUE TITLE
word2idx same for test and train

### ISSUE THREAD

**Issue by erdult** [WayneDW/sentiment_analysis#20]
Arent you supposed to use the same word2idx for test and train?

tokenize_news file is overwriting the word2idx file after preparing the train

**Comment by WayneDW** [comment]
Keeping the same word2idx is better. Thanks for your suggestions.

**Comment by erdult** [comment]
Did you change to same word2idx?

**Comment by WayneDW** [comment]
I forgot the details, sorry about this. Maybe you can just do the way that you think is reasonable.

**Comment by erdult** [comment]
:)
