### ISSUE TITLE
The goldenrocks page isn't working

### ISSUE THREAD

**Issue by sharmisd** [WayneDW/sentiment_analysis#21]
The goldenrocks page isn't working- I get this.

502 Bad Gateway
nginx/1.10.3 (Ubuntu)

**Comment by WayneDW** [comment]
Thanks for your interest. Reuters has updated their website and we didn't get time to fix this. Are you interested in improving the code?

**Comment by sharmisd** [comment]
Yes. I was thinking of extending it.

**Comment by WayneDW** [comment]
Awesome, looking forward to your updates.

**Comment by javierrt942** [comment]
Hi. I'm a novice studying business analytics.    I attempted to run your code, but it breaks when attempting to import "util"  Where can I find this code?  Thanks
