### ISSUE TITLE
Your website is not accessible

### ISSUE THREAD

**Issue by Richar-Du** [WayneDW/sentiment_analysis#23]
I'm sorry, I want to visit your website: http://goldenrocks.me/, however, it shows me "502 bad gateway". Is there any way else I can visit your website?

**Comment by WayneDW** [comment]
Thanks for your interest. I am kind of busy fixing some inconsistencies caused by some updates of the Reuter system. I may fix it later.

**Comment by Richar-Du** [comment]
OK, thanks a lot. Looking forward to your new work.
