### ISSUE TITLE
There is a error which says list out of range

### ISSUE THREAD

**Issue by hardikmeisheri** [WayneDW/sentiment_analysis#3]
`Traceback (most recent call last):
  File "encoder1.py", line 209, in <module>
    mdl = Model()
  File "encoder1.py", line 143, in __init__
    cells, states, logits = model(X, S, M, reuse=False)
  File "encoder1.py", line 93, in model
    inputs = [tf.squeeze(v, [1]) for v in tf.split(axis=1, num_or_size_splits=nsteps, value=words)]
  File "D:\Anaconda2\envs\tensorflow-gpu\lib\site-packages\tensorflow\python\ops\array_ops.py", line 1203, in split
    num = size_splits_shape.dims[0]
IndexError: list index out of range`

**Comment by WayneDW** [comment]
Could you give me more information about this error? Like in which file does this error appear?

**Comment by wangzongshuji** [comment]
I also encountered this error，Did you solve it?

**Comment by hardikmeisheri** [comment]
@WayneDW encoder.py line model inputs = [tf.squeeze(v, [1]) for v in tf.split(axis=1, num_or_size_splits=nsteps, value=words)]

**Comment by hardikmeisheri** [comment]
@wangzongshuji No solution as of yet

**Comment by WayneDW** [comment]
Sorry for the late response, I am afraid that I can't find encoder.py in this repository

**Comment by wangzongshuji** [comment]
[here](https://github.com/WayneDW/Sentiment-Analysis-in-Event-Driven-Stock-Price-Movement-Prediction/issues/3#issuecomment-297849387)，Perfect solution
