### ISSUE TITLE
Update of the input directory?

### ISSUE THREAD

**Issue by Madome31** [WayneDW/sentiment_analysis#5]
Hi,

I would like to get your code running on my computer, but got some trouble with the inputdirectory and filename missmatches.
The outputfile (is stockPrices.json supposed to be stockPrices_raw.json?) of crawler_yahoo_finance.py, is somehow missing, as does the stockReturns.json file of create_label.py.

I would appreciate any help.
Thanks in advance

**Comment by WayneDW** [comment]
the stockPrices.json comes from the old version of my code. It seems to be  stockReturns.json, to make sure, you may need to generate your own file to run this through.

**Comment by WayneDW** [comment]
Hi, @Madome31 , I changed the framework to a new version, it is much more powerful and easier to understand, you are welcome to take a look at it.
