### ISSUE TITLE
sorry ,I don't know which package the "import en"  from ? 

### ISSUE THREAD

**Issue by caoxu915683474** [WayneDW/sentiment_analysis#7]
Hello,MR.Deng! I'm very excited when I saw your project ,but I am a new student in NLP . So,ccould you give me some guidance ? I don't know which package the "import en"  from ?  Is it from nltk? But , I have installed the nltk3.4 package, and I download the corpus of the nltk.  It still doesn't work.

**Comment by Cppowboy** [comment]
https://www.nodebox.net/code/index.php/Linguistics

**Comment by caoxu915683474** [comment]
Oh,thank you! I am in BIT. And I see you are in Tsinghua University. What a small world ! haha

**Comment by WayneDW** [comment]
Hi, @caoxu915683474, @Cppowboy , I changed the framework to a new version, it is much more powerful and easier to understand, you are welcome to take a look at it.
