### ISSUE TITLE
Issue in generating finished.reuters file 

### ISSUE THREAD

**Issue by PRAJ1594** [WayneDW/sentiment_analysis#8]
Using calc_finished_ticker() function the news_reuter.csv is to be transformed to finished.reuters file for reading that file and generating the stockPrices_raw.json file in crawlers_yahoo_finance.py code but then the following error arises:
 fin = open('./input/finished.reuters')

FileNotFoundError: [Errno 2] No such file or directory: './input/finished.reuters'

due to which stockPrices_raw file not generated and henceforth difficult to generate stockPrices.json.

Please advise.

**Comment by gaopinghuang0** [comment]
I think you first need to double check whether "finished.reuters" file is actually generated by `calc_finished_ticker()` function.

**Comment by PRAJ1594** [comment]
it is not getting generated is there any error in the code line?
def calc_finished_ticker():
    os.system("awk -F',' '{print $1}' ./input/news_reuters.csv | sort | uniq > ./input/finished.reuters")

**Comment by gaopinghuang0** [comment]
It's essentially using Python to run a bash script:
`awk -F',' '{print $1}' ./input/news_reuters.csv | sort | uniq > ./input/finished.reuters`

Can you run this script directly on your bash terminal without using Python?
