### ISSUE TITLE
unable to generate the test and training datasets for feature Matrix

### ISSUE THREAD

**Issue by PRAJ1594** [WayneDW/sentiment_analysis#9]
When I am running the getFeatureMatrix.py, the final output is:
We.shape: (2001, 100)

and thereafter 2 0KB files are generated for test and training datasets:
![image](https://user-images.githubusercontent.com/34332413/36988938-3a47de38-20c6-11e8-943c-c94eb777d1b9.png)

**Comment by WayneDW** [comment]
Hi, @PRAJ1594 , I changed the framework to a new version, it is much more powerful and easier to understand, you are welcome to take a look at it.
